server:
  port: 9091

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:192.168.99.100}:${DATASOURCE_PORT:3306}/sc_study?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root123}
#kafka
  kafka:
    bootstrap-servers: 192.168.99.100:9092
    consumer:
      group-id: test-consumer-group
mybatis:
  type-aliases-package: com.cyg.study.entity
  mapper-locations: classpath:dao/*.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
logging:
  level:
    com.cyg.study: debug

#java端口9300，http端口9200
elasticsearch:
  ip: 192.168.99.100
  port: 9300
  pool: 5
  cluster:
    name: docker-cluster