version: '3'
services:
 mysqldbserver:
    image: mysql:5.7
    container_name: mysqldbserver
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ../data/mysql:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root123